---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "../vars.yml"
  tasks:
    - name: Install metallb
      ansible.builtin.import_role:
        name: "plopoyop.kubernetes.metallb"
