---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - "../vars.yml"
  tasks:
    - name: Add echo server helm repo
      kubernetes.core.helm_repository:
        name: "ealenn"
        repo_url: "https://ealenn.github.io/charts"

    - name: Install echo helm package
      kubernetes.core.helm:
        name: "echo-server"
        namespace: "echo-server"
        chart_ref: "ealenn/echo-server"
        create_namespace: true
        update_repo_cache: true
        wait: true
        values:
          service:
            type: "LoadBalancer"

    - name: "Wait for 'metallb' namespace to be active."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "{{ metallb_namespace }}"
      register: namespace_metallb
      until:
        - namespace_metallb.resources | length > 0
        - namespace_metallb.resources[0].status.phase == "Active"
      retries: 30
      delay: 5

    - name: "Assert that 'metallb' namespace is active."
      ansible.builtin.assert:
        that:
          - namespace_metallb.resources | length > 0
          - namespace_metallb.resources[0].status.phase == "Active"
        fail_msg: "Namespace '{{ metallb_namespace }}' is not active."

    - name: "Wait for 'echo-server' service to have an ip address."
      kubernetes.core.k8s_info:
        kind: Service
        name: "echo-server"
        namespace: "echo-server"
      register: service
      until: service.resources[0].status.loadBalancer.ingress[0].ip is defined
      retries: 30
      delay: 5

    - name: "Assert that 'echo-server' service has an ip address."
      ansible.builtin.assert:
        that: service.resources[0].status.loadBalancer.ingress[0].ip is defined
        fail_msg: "Service 'echo-server' has no ip address."
