---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Pause for job to complete."
      ansible.builtin.pause:
        seconds: 5

    - name: Get 'selfsigned-issuer' ClusterIssuer.
      kubernetes.core.k8s_info:
        kind: ClusterIssuer
        name: "selfsigned-issuer"
      register: issuer

    - name: Assert that 'selfsigned-issuer' ClusterIssuer is removed
      ansible.builtin.assert:
        that: issuer['resources'] == []

    - name: Get 'letsencrypt-staging' ClusterIssuer.
      kubernetes.core.k8s_info:
        kind: ClusterIssuer
        name: "letsencrypt-staging"
      register: issuer

    - name: Assert that 'letsencrypt-staging' ClusterIssuer is removed
      ansible.builtin.assert:
        that: issuer['resources'] == []

    - name: "Get 'cert-manager' namespace info."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "cert-manager"
      register: namespace_cert_manager

    - name: Assert that 'cert-manager' namespace is removed
      ansible.builtin.assert:
        that: namespace_cert_manager['resources'] == []
