---
namespace: plopoyop

name: kubernetes

version: 0.0.1

readme: README.md
authors:
  - Clément Hubert <clement@plopoyop.me>

description: Ansible collection to configure various role on a Kubernetes cluster

license_file: 'LICENSE'

tags:
  - cloud
  - kubernetes
  - cluster
  - infrastructure

dependencies:
  kubernetes.core: ">=5.1.0"

repository: https://github.com/plopoyop/ansible-collection-kubernetes
issues: https://github.com/plopoyop/ansible-collection-kubernetes/issues

# A list of file glob-like patterns used to filter any files or directories that should not be included in the build
# artifact. A pattern is matched from the relative path of the file or directory of the collection directory. This
# uses 'fnmatch' to match the files or directories. Some directories and files like 'galaxy.yml', '*.pyc', '*.retry',
# and '.git' are always filtered. Mutually exclusive with 'manifest'
build_ignore: []
