namespace: plopoyop
name: kubernetes
version: 3.2.0
readme: README.md
authors:
  - Clément Hubert <clement@plopoyop.me>
description: Ansible collection to configure various role on a Kubernetes cluster
license_file: LICENSE
tags:
  - cloud
  - kubernetes
  - cluster
  - infrastructure
dependencies:
  kubernetes.core: '>=5.1.0'
repository: 'https://github.com/plopoyop/ansible-collection-kubernetes'
issues: 'https://github.com/plopoyop/ansible-collection-kubernetes/issues'
build_ignore: []
