---
version: '3'

vars:
  ROLES_LIST: ["metallb", "traefik"]

tasks:
  default:
    cmds:
      - task -l
    silent: true

  prepare:
    desc: "Prepare development environment"
    cmds:
      - task: pre-commit
      - install-kind-cloud
    generates:
      - .devenv/bin/cloud-provider-kind

  pre-commit:
    desc: "Install pre-commit hooks"
    cmds:
      - pre-commit install
    sources:
      - .git/hooks/pre-commit
      - .pre-commit-config.yaml
    generates:
      - .git/hooks/pre-commit
    method: checksum

  check:
    desc: "Run pre-commit hooks"
    cmds:
      - pre-commit run -a

  lint:
    desc: "Run pre-commit hooks"
    cmds:
      - yamllint .
      - ansible-lint

  test:role:*:
    desc: "Run tests on a specific role"
    dir: 'roles/{{.ROLE_NAME}}'
    deps:
      - prepare
    cmds:
      - molecule test --all
    vars:
      ROLE_NAME: '{{index .MATCH 0}}'

  test:roles:all:
    desc: "Run tests on all roles"
    cmds:
      - for: { var: ROLES_LIST }
        task: test:role:{{.ITEM}}

  gen-doc:role:*:
    desc: "Run tests on a specific role"
    dir: 'roles/{{.ROLE_NAME}}'
    cmds:
      - ansible-doctor -f
    vars:
      ROLE_NAME: '{{index .MATCH 0}}'

  gen-doc:roles:all:
    desc: "Generate doc"
    cmds:
      - for: { var: ROLES_LIST }
        task: gen-doc:role:{{.ITEM}}
