---
version: '3'

vars:
  ROLES_LIST: ["metallb", "external_dns", "traefik", "cert_manager", "mongodb"]

tasks:
  default:
    cmds:
      - task -l
    silent: true

  prepare:
    desc: "Prepare development environment"
    cmds:
      - task: pre-commit
      - mkdir -p ${ANSIBLE_GALAXY_ROLES_PATH}
      - mkdir -p ${ANSIBLE_GALAXY_COLLECTIONS_PATH}
      - ${DEVBOX_CONFIG_DIR}/install-kind-cloud.sh
    generates:
      - ${DEVBOX_PROJECT_ROOT}/.devbox/bin/cloud-provider-kind

  pre-commit:
    desc: "Install pre-commit hooks"
    cmds:
      - pre-commit install
    sources:
      - .git/hooks/pre-commit
      - .pre-commit-config.yaml
    generates:
      - .git/hooks/pre-commit
    method: checksum

  check:
    desc: "Run pre-commit hooks"
    cmds:
      - pre-commit run -a

  lint:
    desc: "Run lint"
    cmds:
      - yamllint .
      - ansible-lint
      - ruff check plugins/ tests/

  test:modules:
    desc: "Run pytest for ansible modules"
    cmds:
      - PYTHONPATH=${PYTHONPATH}:${PWD} pytest tests/

  test:role:*:
    desc: "Run tests on a specific role"
    dir: 'roles/{{.ROLE_NAME}}'
    deps:
      - prepare
    cmds:
      - molecule test --all
    vars:
      ROLE_NAME: '{{index .MATCH 0}}'

  test:roles:all:
    desc: "Run tests on all roles"
    cmds:
      - for: { var: ROLES_LIST }
        task: test:role:{{.ITEM}}

  gen-doc:role:*:
    desc: "Run tests on a specific role"
    dir: 'roles/{{.ROLE_NAME}}'
    cmds:
      - ansible-doctor -f
    vars:
      ROLE_NAME: '{{index .MATCH 0}}'

  gen-doc:roles:all:
    desc: "Generate doc"
    cmds:
      - for: { var: ROLES_LIST }
        task: gen-doc:role:{{.ITEM}}
