---
version: '3'

vars:
  ROLES_LIST: ["metallb"]

tasks:
  default:
    cmds:
      - task -l
    silent: true

  pre-commit:
    desc: "Install pre-commit hooks"
    cmds:
      - pre-commit install
    sources:
      - .git/hooks/pre-commit
      - .pre-commit-config.yaml
    generates:
      - .git/hooks/pre-commit
    method: checksum

  check:
    desc: "Run pre-commit hooks"
    cmds:
      - pre-commit run -a

  lint:
    desc: "Run pre-commit hooks"
    cmds:
      - yamllint .
      - ansible-lint

  test:role:*:
    desc: "Run tests on a specific role"
    dir: 'roles/{{.ROLE_NAME}}'
    cmds:
      - molecule test --all
    vars:
      ROLE_NAME: '{{index .MATCH 0}}'

  test:roles:all:
    desc: "Run tests on all roles"
    cmds:
      - for: { var: ROLES_LIST }
        task: test:role:{{.ITEM}}
