---
- name: Include setup when enabled
  ansible.builtin.include_tasks: "setup.yml"
  when: metallb_enabled

- name: Include cleanup when disabled
  ansible.builtin.include_tasks: "cleanup.yml"
  when: not metallb_enabled
