---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "../vars.yml"
  tasks:
    - name: Build a kind cluster (wait for control plane).
      ansible.builtin.command: >-
        kind create cluster
        --wait 300s
        --name molecule-test
        --kubeconfig {{ kubeconfig }}
      changed_when: true

    - name: Install metallb
      ansible.builtin.import_role:
        name: "plopoyop.kubernetes.metallb"
