---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - "../vars.yml"
  tasks:
    - name: "Wait for 'metallb' namespace to be removed."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "{{ metallb_namespace }}"
      register: namespace_metallb
      until: namespace_metallb.resources | length == 0
      retries: 30
      delay: 5

    - name: "Assert that 'metallb' namespace is removed."
      ansible.builtin.assert:
        that: namespace_metallb.resources | length == 0
        fail_msg: "Namespace '{{ metallb_namespace }}' is still present."
