---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Install traefik
      ansible.builtin.import_role:
        name: "traefik"
  vars:
    traefik_ingress_enabled: false
