---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Wait for 'traefik' namespace to be removed."
      kubernetes.core.k8s_info:
        kind: "Namespace"
        name: "ingress-traefik-controller"
      register: namespace_traefik
      until: namespace_traefik.resources | length == 0
      retries: 30
      delay: 5

    - name: "Assert that 'traefik' namespace is removed."
      ansible.builtin.assert:
        that: namespace_traefik.resources | length == 0
        fail_msg: "Namespace 'ingress-traefik-controller' is still present."

    - name: "Wait for 'traefik' ingress class to be removed."
      kubernetes.core.k8s_info:
        kind: "IngressClass"
        name: "traefik"
      register: ingressclass
      until: ingressclass.resources[0] is not defined
      retries: 30
      delay: 5

    - name: "Assert that 'traefik' ingress class is removed."
      ansible.builtin.assert:
        that: ingressclass.resources[0] is not defined
        fail_msg: "IngressClass 'traefik' is still present."

    - name: "Wait for 'traefik' service to be removed."
      kubernetes.core.k8s_info:
        kind: "Service"
        name: "traefik"
        namespace: "ingress-traefik-controller"
      register: service
      until: service.resources[0].status.loadBalancer.ingress is not defined
      retries: 30
      delay: 5

    - name: "Assert that 'traefik' service is removed."
      ansible.builtin.assert:
        that: service.resources[0].status.loadBalancer.ingress is not defined
        fail_msg: "Service 'traefik' is still present with a load balancer ingress."
