---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    cert_manager_acme_production_enabled: false
  tasks:
    - name: "Install cert-manager"
      ansible.builtin.import_role:
        name: "cert_manager"

    - name: "Create test certificate"
      kubernetes.core.k8s:
        state: "present"
        definition:
          apiVersion: "cert-manager.io/v1"
          kind: "Certificate"
          metadata:
            name: test-cert
            namespace: default
          spec:
            secretName: test-cert-tls
            issuerRef:
              name: selfsigned-issuer
              kind: ClusterIssuer
            commonName: example.com
            dnsNames:
              - www.example.com
