---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Pause for job to complete."
      ansible.builtin.pause:
        seconds: 5

    - name: "Get 'cert-manager' namespace info."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "cert-manager"
      register: namespace

    - name: Assert that 'cert-manager' namespace is active
      ansible.builtin.assert:
        that: namespace['resources'][0]['status']['phase'] == "Active"

    - name: Get 'selfsigned-issuer' ClusterIssuer.
      kubernetes.core.k8s_info:
        kind: ClusterIssuer
        name: "selfsigned-issuer"
      register: issuer

    - name: Assert that 'selfsigned-issuer' ClusterIssuer is defined
      ansible.builtin.assert:
        that: issuer['resources'][0] is defined

    - name: Get 'letsencrypt-staging' ClusterIssuer.
      kubernetes.core.k8s_info:
        kind: ClusterIssuer
        name: "letsencrypt-staging"
      register: issuer

    - name: Assert that 'letsencrypt-staging' ClusterIssuer is defined
      ansible.builtin.assert:
        that: issuer['resources'][0] is defined

    - name: Get 'letsencrypt-prod' ClusterIssuer.
      kubernetes.core.k8s_info:
        kind: ClusterIssuer
        name: "letsencrypt-prod"
      register: issuer

    - name: Assert that 'letsencrypt-prod' ClusterIssuer is defined
      ansible.builtin.assert:
        that: issuer['resources'][0] is not defined

    - name: Get 'test' Certificate.
      kubernetes.core.k8s_info:
        kind: "Certificate"
        name: "test-cert"
        namespace: default
      register: cert

    - name: Assert that 'test' Certificate is issued
      ansible.builtin.assert:
        that: cert['resources'][0].status.conditions[0].status
