---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Wait for 'crowdsec' namespace to be removed."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "crowdsec"
      register: namespace_crowdsec
      until: namespace_crowdsec.resources | length == 0
      retries: 30
      delay: 5
      changed_when: false

    - name: "Assert that 'crowdsec' namespace is removed."
      ansible.builtin.assert:
        that: namespace_crowdsec.resources | length == 0
        fail_msg: "Namespace 'crowdsec' is still present."
