---
galaxy_info:
  description: Install traefik ingress controller on kubernetes
  role_name: traefik
  author: Clément Hubert

  license: MPL-2.0

  min_ansible_version: "2.17"

  galaxy_tags:
    - kubernetes
    - traefik
    - ingress

dependencies: []
