---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Kill cloud provider.
      ansible.builtin.raw: >-
        pkill -f "cloud-provider-kind"
      failed_when: false
      changed_when: false

    - name: Delete the kind cluster.
      ansible.builtin.command: >-
        kind delete cluster
        --name molecule-test
        --kubeconfig {{ kubeconfig }}
      changed_when: false
