---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Wait for 'traefik' namespace to be active."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "ingress-traefik-controller"
      register: namespace_traefik
      until:
        - namespace_traefik.resources | length > 0
        - namespace_traefik.resources[0].status.phase == "Active"
      retries: 30
      delay: 5

    - name: "Assert that 'traefik' namespace is active."
      ansible.builtin.assert:
        that:
          - namespace_traefik.resources | length > 0
          - namespace_traefik.resources[0].status.phase == "Active"
        fail_msg: "Namespace 'ingress-traefik-controller' is not active."

    - name: Multiple checks on instances
      ansible.builtin.include_tasks: ./tasks/check_instances.yml
      loop:
        - "traefik-public"
        - "traefik-private"
      loop_control:
        loop_var: instance_to_check
