---
galaxy_info:
  description: "Install CrowdSec on kubernetes"
  role_name: "crowdsec"
  author: "Clément Hubert"

  license: "MLP2"

  min_ansible_version: "2.1"

  galaxy_tags:
    - "kubernetes"
    - "crowdsec"
    - "security"
    - "ids"
    - "ips"

dependencies: []
