name: Renovate

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v39.0.3
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
